### ISSUE TITLE
Unable to read Documentation Samples

### ISSUE THREAD

**Issue by matjames007** [slashroots/harvest-v2#46]
I am unable to read any of the samples given by the documentation because of the colours.  A screenshot is shown below:
<img width="341" alt="screen shot 2016-11-13 at 5 51 05 pm" src="https://cloud.githubusercontent.com/assets/1425164/20249572/0bb05164-a9ca-11e6-9253-ae4f82f82671.png">

**Comment by matjames007** [comment]
Also what is `imagine getCropById x 50!' ? @thinkking

**Comment by leechristophermurray** [comment]
@matjames007 the styling, being a separate feature is what would make the samples visible. at the moment, our css is overriding redoc's css and causing this issue.

Due to the length of a response for getting a single record is, It would not be very feasible to add more than one for the getAll\* functions. "`imagine getCropById x 50!'" is used just as a placeholder for now.

**Comment by paradoxxjm** [comment]
Closing this issue as it is now captured by issue #80 "API Documentation Styling"
